ldap1:
  image: bahaaldine/docker-ldap
  volumes:
    - "./conf/ldap:/tmp/files"
  ports:
    - "389:389"

zookeeper1:
  image: bahaaldine/docker-zookeeper
  volumes:
    - "./conf/kafka/server1:/etc/kafka"
    - "./logs/zookeeper1:/opt/kafka/logs/"
  ports:
    - "2181:2181"
  extra_hosts:
    - "brokers:192.168.99.100"

kafka1:
  image: bahaaldine/docker-kafka
  volumes:
    - "./conf/kafka/server1:/etc/kafka"
    - "./logs/kafka1:/opt/kafka/logs/"
  extra_hosts:
    - "brokers:192.168.99.100"
  ports:
    - "9092:9092"

kafka2:
  image: bahaaldine/docker-kafka
  volumes:
    - "./conf/kafka/server2:/etc/kafka"
    - "./logs/kafka2:/opt/kafka/logs/"
  extra_hosts:
    - "brokers:192.168.99.100"
  links:
    - "kafka1"
  ports:
    - "9093:9093"

logstashprocessor1:
  build: images/logstash
  volumes:
    - "./conf/logstash/processor:/etc/logstash"
    - "./conf/security:/etc/logstash/security"
    - "./logs/logstash-processor1:/var/log/logstash"
  links:
    - kafka1
  ports:
    - "5043:5043"

elasticsearch1:
  build: images/elasticsearch/
  ports:
    - "9200:9200"
  volumes:
#    - "./logs/elasticsearch1:/usr/share/elasticsearch/logs/"
    - "./conf/elasticsearch:/usr/share/elasticsearch/config"
#    - "./data:/usr/share/elasticsearch/data/"
    - "./backup:/tmp/backup"
  links:
    - ldap1:ldap
  extra_hosts:
    - "elasticsearch:192.168.99.100"
    - "ldap:192.168.99.100"
logstashindexer1:
  build: images/logstash
  volumes:
    - "./conf/logstash/indexer:/etc/logstash"
    - "./logs/logstash-indexer1:/var/log/logstash"
    - "./conf/logstash/indexer/templates:/etc/logstash/templates"
  links:
    - elasticsearch1
  extra_hosts:
    - "brokers:192.168.99.100"
    - "elasticsearch:192.168.99.100"

logstashforwarder:
  build: images/forwarder
  volumes:
    - "./conf/logstash/forwarder:/etc/logstash-forwarder"
    - "./conf/security:/etc/logstash-forwarder/security"
    - "./logs/logstash-forwarder1:/tmp/logs/"
    - "./source:/tmp/source"
  extra_hosts:
    - "processors:192.168.99.100"
kibana1:
  build: images/kibana
  ports:
    - "5601:5601"
  volumes:
    - "./logs/kibana:/var/log/kibana"
    - "./conf/kibana:/opt/kibana/config"
  extra_hosts:
    - "elasticsearch:192.168.99.100"